[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "ccxt>=4.4.85",
    "flask>=3.1.1",
    "telegram>=0.0.1",
    "telethon>=1.40.0",
]
